### ISSUE TITLE
cannot push functions

### ISSUE THREAD

**Issue by revolucas** [luapower/thread#7]
It seems I'm able to push any lua type except functions.

For example:
th:push(function() end, time.time() + 1)

I'm unsure if the thread silently quits execution or is just stuck in a forever loop.

Even the test_pool() example that is commented out in the thread_test.lua will not work. It just sits at 'waiting for task 1' forever.

I'm running Windows 8 with x64 version of luaJIT 2.1.0 beta 3. I also tried the luajit binaries from here, with the same result: https://github.com/luapower/luajit

If I replace the function with a string, number or table, it seems to work.

**Comment by capr** [comment]
You might have hit https://github.com/luapower/pthread/issues/1 (I don't have much time to investigate that at the moment). Please try it with luajit32.

**Comment by revolucas** [comment]
```
time to create 1000 pthreads  : 0.14s   7105 pthreads/s
time to create  100 states    : 0.01s  10951 states/s
time to create   10 threads   : 0.05s    219 threads/s
queue test: 10*1000 -> 10*1000, queue size: 1000, time: 236ms
queue test: 1*10000 -> 1*10000, queue size: 1000, time: 198ms
queue test: 1*10000 -> 10*1000, queue size: 1000, time: 726ms
queue test: 10*1000 -> 1*10000, queue size: 1000, time: 690ms
queue test: 1*10000 -> 10*1000, queue size: 1, time: 794ms
queue test: 10*1000 -> 1*10000, queue size: 1, time: 805ms
push resultwaiting for task     1
        Ptrue   1
ANIC: unprotected error in call to Lua API (attempt to index a nil value)
Press any key to continue . . .
```


Hmm, this is what I get with luaJIT and pthread bins from mingw32 folder when uncommenting test_pool(). I can't really test my application in 32 bit because it's an engine dependent on other libraries which I only have x64 binaries for.  Seems x64 bins do not show this error.

I recall seeing that there are issues with x64, but I haven't had problems other than this. Both pthread_test.lua and thread_test.lua worked out-of-box. It wasn't until I wanted to use thread pools that I have ran into this issue. I have a dedicated thread in my engine that uses luajit FFI with OpenAL and Vorbis to play audio; it has worked flawlessly thus far.

**Comment by capr** [comment]
I'm pretty sure the bug is still there (just ran thread_test.lua on Win7, got the random crashes pretty quick).

**Comment by revolucas** [comment]
Really? I can run this dozens of times without any crashes: 
https://drive.google.com/open?id=1Kh9ryWETXpvu9BRox5cllIsQyDxByaRC

luajit compiled in Visual Studio

**Comment by revolucas** [comment]
I found the problem. luastate.lua's M.get, for functions, uses string.dump, but the queue's luastate didn't open the string library, so _G.string is nil.

```
M.getglobal(L, 'string')
M.getfield(L, -1, 'dump')
```

To clarify, I fixed it by adding:
`state:openlibs('string')`
in thread.lua's thread.queue function
